server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(svg|woff2?|png|jpe?g|webp|ico|css|js|json|clsp|clvm|hex)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_comp_level 5;
    gzip_types text/css application/javascript image/svg+xml application/json text/plain;
}
